import Head from "next/head"
import { Sidebar } from "./Sidebar"


export const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>CRM - Administrador de clientes</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex bg-gray-600 min-h-screen">
                <Sidebar />

                <main className="sm:min-h-screen p-5">

                    {children}
                </main>
            </div>

        </>
    )
}
